create database suc_db;
use suc_db;

-- MySQL Script generated by MySQL Workbench
-- Sun Jun 11 19:41:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Suc_DB
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
-- drop table user; 

CREATE TABLE IF NOT EXISTS `User` (
    `idUser` 		BIGINT(32) 	NOT NULL AUTO_INCREMENT,
    `name` 			VARCHAR(50) NOT NULL,
    `surname` 		VARCHAR(50) NOT NULL,
    `mail` 			VARCHAR(50) NOT NULL,
    `phone` 		VARCHAR(20) NULL,
--  `state` 		INT 		NULL,
    `bornDate` 		DATE 		NULL,
    `role` 			INT 		NOT NULL,
    `pass` 			VARCHAR(64) NOT NULL,
    `alias` 		VARCHAR(20) NOT NULL UNIQUE,
    `docNum` 		VARCHAR(13) NULL,
    `street` 		VARCHAR(50) NULL,
    `streetNumber`  INT 		NULL,
    `floor` 		VARCHAR(10) NULL,
    `door` 			VARCHAR(20) NULL,
    PRIMARY KEY (`idUser`)
)  ENGINE=InnoDB;

SHOW WARNINGS;


-- -----------------------------------------------------
-- Table `Notification`
-- -----------------------------------------------------
-- drop table notification;

CREATE TABLE IF NOT EXISTS `Notification` (
  `idNotification` 	 	BIGINT(32) 	NOT NULL AUTO_INCREMENT,
  `notificationType` 	INT 	 	NOT NULL,
  `notificationStatus`  INT 	 	NOT NULL,
  `title` 			    VARCHAR(50) NOT NULL,
  `description` 		LONGTEXT 	NULL,
  `idUser` 			    BIGINT(32) 	NOT NULL,
  PRIMARY KEY (`idNotification`),
  foreign key (idUser) references User (idUser),
  INDEX `idUser_idx` (`idUser` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Diner`
-- -----------------------------------------------------
-- Drop table diner;

CREATE TABLE IF NOT EXISTS `Diner` (
  `idDiner` 		BIGINT(32) 	NOT NULL AUTO_INCREMENT,
  `name` 			VARCHAR(80)  NOT NULL,
  `state` 		  	INT 		 NOT NULL,
  `street` 			VARCHAR(50)  NULL,
  `streetNumber` 	INT 		 NULL,
  `floor` 			VARCHAR(10)  NULL,
  `door` 			VARCHAR(20)  NULL,
  `latitude` 		FLOAT 	 	 NULL,
  `longitude` 		FLOAT 		 NULL,
  `zipCode` 		VARCHAR(5) 	 NULL,
  `phone` 			VARCHAR(20)  NULL,
  `description` 	LONGTEXT 	 NULL,
  `link` 			VARCHAR(100) NULL,
  `mail` 			VARCHAR(50)  NOT NULL,
  PRIMARY KEY (`idDiner`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Assistant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assistant` (
  `idAssistant`   	  BIGINT(32) 	NOT NULL AUTO_INCREMENT,
  `name` 		  	  VARCHAR(50) 	NOT NULL,
  `surname` 	  	  VARCHAR(50) 	NOT NULL,
  `bornDate` 	  	  DATE 			NOT NULL,
  `street` 		  	  VARCHAR(50) 	NULL,
  `streetNumber`  	  INT 			NULL,
  `floor` 		  	  VARCHAR(10) 	NULL,
  `door` 		  	  VARCHAR(20) 	NULL,
  `zipCode` 	  	  CHAR(5) 		NULL,
-- `state` 		  	  INT 			NOT NULL,
  `phone` 		  	  VARCHAR(20) 	NULL,
  `contactName`   	  VARCHAR(50) 	NULL,
  `scholarship`   	  VARCHAR(50) 	NULL,
  `eatAtOwnHouse` 	  bool 			NULL,
  `economicSituation` VARCHAR(80) 	NULL,
  `celiac` 			  bool NULL default false,
  `diabetic` 		  bool NULL default false,
  `document` 		  VARCHAR(13) NULL,
`latitude` 		FLOAT 	 	 NULL,
  `longitude` 		FLOAT 		 NULL,
  PRIMARY KEY (`idAssistant`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `FoodType`
-- -----------------------------------------------------
-- drop table FoodType;

CREATE TABLE IF NOT EXISTS `FoodType` (
  `idFoodType`  BIGINT(32) 	 	NOT NULL auto_increment,
  `code` 	    VARCHAR(10) 	NOT NULL UNIQUE,
  `name`  	    VARCHAR(50) NOT NULL,
  `description` LONGTEXT 	NOT NULL,
  `perishable`  bool 		NOT NULL default false,
  `celiac`      bool 		NOT NULL default false,
  `diabetic`    bool 		NOT NULL default false,
  PRIMARY KEY (`idFoodType`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `InputType`
-- -----------------------------------------------------
-- drop table InputType;

CREATE TABLE IF NOT EXISTS `InputType` (
  `idInputType`  BIGINT(32) 			NOT NULL auto_increment,
  `code` 	     VARCHAR(10) 		NOT NULL UNIQUE,
  `name`  	     VARCHAR(50) 	NOT NULL,
  `description`  LONGTEXT 		NULL,
  PRIMARY KEY (`idInputType`))
ENGINE = InnoDB;

SHOW WARNINGS;


-- -----------------------------------------------------
-- Table `Donation`
-- -----------------------------------------------------
-- drop table donation;

CREATE TABLE IF NOT EXISTS `Donation` (

  `idDonation` 		BIGINT(32) 	NOT NULL AUTO_INCREMENT,
  `idUserSender` 		BIGINT(32) NOT NULL COMMENT 'Colaborador que realiza un donación',
  `idDinerReceiver` 		BIGINT(32) NOT NULL,
  `title` 			VARCHAR(50) NOT NULL,
  `description` 	LONGTEXT NULL,
  `creationDate` 		DATE 	 NULL,
  `status` 		INTEGER(3) 	 NOT NULL,
  PRIMARY KEY (`idDonation`),
  FOREIGN KEY (idUserSender) 	REFERENCES User  (idUser),
  FOREIGN KEY (idDinerReceiver) 	REFERENCES Diner (idDiner),
  INDEX `idUserSender_idx` (`idUserSender`),
  INDEX `idDinerReceiver_idx` (`idDinerReceiver`))   	
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `DonationItem`
-- -----------------------------------------------------
-- drop table donationitem; 

CREATE TABLE IF NOT EXISTS `DonationItem` (
  `idDonationItem` 		BIGINT(32) 	NOT NULL AUTO_INCREMENT,
  `idDonation` 	BIGINT(32) 	NOT NULL,
  `inputType` 	INT 	NULL,
  `foodType` 	INT 	NULL,
  `quantity` 	FLOAT 	NOT NULL,
  `unit` 		CHAR(5) NULL,
	  `description` 		VARCHAR(80)  NOT NULL,
  PRIMARY KEY (`idDonationItem`, `idDonation`),
  foreign key (idDonation) references Donation (idDonation) )
ENGINE = InnoDB;

SHOW WARNINGS;


-- -----------------------------------------------------
-- Table `Family`
-- -----------------------------------------------------
-- drop table family;

CREATE TABLE IF NOT EXISTS `Family` (
  `idFamily` 	BIGINT(32) 		 NOT NULL auto_increment,
  `idAssistant` BIGINT(32)	 NOT NULL,
  `Description` VARCHAR(100) NULL,
  PRIMARY KEY (`idFamily`, `idAssistant`),
  foreign key (idAssistant) references Assistant (idAssistant))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Photo`
-- -----------------------------------------------------
-- drop table Photo;

CREATE TABLE IF NOT EXISTS `DinerPhoto` (
  `idDiner` BIGINT(32) 	NOT NULL,
  `idPhoto` BIGINT(32) 		NOT NULL AUTO_INCREMENT,
  `url` 	LONGTEXT 	NOT NULL,
  PRIMARY KEY (`idPhoto`, `idDiner`),
  foreign key (idDiner) references Diner (idDiner),
  INDEX `idDiner_idx` (`idDiner` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Event`
-- -----------------------------------------------------
-- drop table Event;

CREATE TABLE IF NOT EXISTS `Event` (
  `idEvent` 	 BIGINT(32) 	  NOT NULL AUTO_INCREMENT,
  `name` 		 varchar(50)  NOT NULL,
  `street` 		 varchar(50)  NULL,
  `streetNumber` INT 		  NULL,
  `floor` 		 varchar(10)  NULL,
  `door` 		 varchar(20)  NULL,
  `zipCode` 	 CHAR(5) 	  NULL,
  `phone` 		 varchar(20)  NULL,
  `date` 		 DATETIME 		  NOT NULL,
	`latitude` 		FLOAT 	 	 NULL,
  `longitude` 		FLOAT 		 NULL,
  `link` 		 longtext     NULL,
  `description`  LONGTEXT  	  NOT NULL,
  `idDiner` 	 BIGINT(32)  	  NOT NULL,
  PRIMARY KEY (`idEvent`),
  foreign key (idDiner) references Diner (idDiner))
ENGINE = InnoDB;

SHOW WARNINGS;


-- -----------------------------------------------------
-- Table `DinerFood`
-- -----------------------------------------------------
-- drop table DinerFood;

CREATE TABLE IF NOT EXISTS `DinerFood` (
  `idDinerFood`    BIGINT(32) 			NOT NULL auto_increment,
  `creationDate`   DATE 		NOT NULL,
  `idDiner` 	   BIGINT(32) 	NOT NULL,
  `idFoodType`     BIGINT(32) 			NOT NULL,
  `name` 		   VARCHAR(50)	NOT NULL,
  `description`    LONGTEXT 	NULL,
  `quantity` 	   FLOAT 		NULL NULL,
  `unity` 		   VARCHAR(5) 		NULL NULL,
  `endingDate` 	   DATE 		NULL,
  `expirationDate` DATE	 		NULL,
  PRIMARY KEY (`idDinerFood`),
  foreign key (idDiner)    references Diner    (idDiner),
  foreign key (idFoodType) references FoodType (idFoodType),  
  INDEX `idFoodType_idx` (`idFoodType` ASC),
  INDEX `idDiner_idx`    (`idDiner` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `DinerRequest`
-- -----------------------------------------------------
-- drop table DinerRequest;

CREATE TABLE IF NOT EXISTS `DinerRequest` (
  `idDinerRequest`  BIGINT(32) 	NOT NULL AUTO_INCREMENT,
  `idDiner` 		BIGINT(32) 	NOT NULL,
  `title` 			VARCHAR(50) NOT NULL,
  `description` 	LONGTEXT 	NOT NULL,
  `creationDate` 		DATE 		NOT NULL ,
  `status` 		INTEGER(2) 		NOT NULL,
  PRIMARY KEY (`idDinerRequest`),
  foreign key (idDiner) references Diner (idDiner),
  INDEX `idDiner_idx` (`idDiner` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `DinerInput`
-- -----------------------------------------------------
-- drop table DinerInput;

CREATE TABLE IF NOT EXISTS `DinerInput` (
  `idDinerInput`   BIGINT(32) 			NOT NULL auto_increment,
  `idDiner` 	   BIGINT(32) 	NOT NULL,
  `idInputType`    BIGINT(32) 			NOT NULL,
  `name` 		   VARCHAR(50)  NULL,
  `size`           VARCHAR(50) 	NULL,
  `genderType` 	   CHAR 		NOT NULL,
  `quantity` 	   INT			NOT NULL,
  `description`    LONGTEXT 	NULL,
  PRIMARY KEY (`idDinerInput`),
  foreign key (idDiner)     references Diner    (idDiner),
  foreign key (idInputType) references InputType (idInputType),  
  INDEX `idInputType_idx` (`idInputType` ASC),
  INDEX `idDiner_idx` (`idDiner` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UserDiner`
-- -----------------------------------------------------
-- drop table UserDiner;

CREATE TABLE IF NOT EXISTS `UserDiner` (
    `idDiner` 	BIGINT(32) NOT NULL,
    `idUser` 	BIGINT(32) NOT NULL,
    `active` 	BOOL 	 NOT NULL DEFAULT false,
    PRIMARY KEY (`idDiner` , `idUser`),
    FOREIGN KEY (idDiner) REFERENCES Diner (idDiner),
    FOREIGN KEY (idUser)  REFERENCES User  (idUser))
ENGINE=InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `DinerAssistant`
-- -----------------------------------------------------
-- drop table DinerAssistant;

CREATE TABLE IF NOT EXISTS `DinerAssistant` (
  `idDiner` 	BIGINT(32) NOT NULL,
  `idAssistant` BIGINT(32) NOT NULL,
  `active` 		bool default false,
  PRIMARY KEY (`idDiner`, `idAssistant`),
  foreign key (idDiner)     references Diner     (idDiner),
  foreign key (idAssistant) references Assistant (idAssistant),
  INDEX `idAssistant_idx` (`idAssistant` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EventPhoto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventPhoto` (
    `idEvent` BIGINT(32) 	NOT NULL,
    `idPhoto` BIGINT(32) 		NOT NULL AUTO_INCREMENT,
	`url` 	  LONGTEXT 	NOT NULL,
    PRIMARY KEY (`idEvent` , `idPhoto`),
    FOREIGN KEY (idEvent) REFERENCES Event (idEvent),
    FOREIGN KEY (idPhoto) REFERENCES DinerPhoto (idPhoto),
    INDEX `idPhoto_idx` (`idPhoto` ASC)
)  ENGINE=InnoDB;

SHOW WARNINGS;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
